openapi: 3.0.3
info:
  title: OpenAPI schema for template test-k8s-widget
components:
  schemas:
    variables:
      type: object
      properties:
        namespace:
          title: Namespace
          type: string
          description: Namespace for deployment
          x-walrus-ui:
            widget: NamespaceSelect
        secret:
          title: Secret
          type: string
          description: Kubernetes Secret
          x-walrus-ui:
            widget: SecretSelect
        configmap:
          title: ConfigMap
          type: string
          description: Kubernetes ConfigMap
          x-walrus-ui:
            widget: ConfigMapSelect
        storageclass:
          title: StorageClass
          type: string
          description: Kubernetes StorageClass
          x-walrus-ui:
            widget: StorageClassSelect
        
